#!/bin/bash
set -e

# Input parameters
GEMINI_API_KEY="$1"
SOURCE_FOLDER="$2"

# Hardcoded configuration
LANGUAGES="ar,de,es,fr,ja,nl,pt,zh-Hans,zh-Hant,it,ko,sv,hi,pl,tr,ru"

echo "🌍 Starting LLM-Powered Localization Workflow"
echo "================================================"

# Validate inputs
if [ -z "$GEMINI_API_KEY" ]; then
    echo "❌ Error: Gemini API key is required"
    exit 1
fi

if [ -z "$SOURCE_FOLDER" ]; then
    echo "❌ Error: Source folder is required"
    exit 1
fi

# Navigate to workspace
cd "$GITHUB_WORKSPACE"

# Validate source folder exists
if [ ! -d "$SOURCE_FOLDER" ]; then
    echo "❌ Error: Source folder '$SOURCE_FOLDER' does not exist"
    exit 1
fi

# Check for .xcstrings files
XCSTRINGS_COUNT=$(find "$SOURCE_FOLDER" -name "*.xcstrings" | wc -l)
if [ "$XCSTRINGS_COUNT" -eq 0 ]; then
    echo "❌ Error: No .xcstrings files found in '$SOURCE_FOLDER'"
    exit 1
fi

echo "✅ Found $XCSTRINGS_COUNT .xcstrings file(s) in $SOURCE_FOLDER"

# Step 1: Enforce 100% translation - generate JSON files for LLM
echo ""
echo "📋 Step 1: Analyzing missing translations..."
python /action/enforce_100%_translation.py --folder "$SOURCE_FOLDER" --languages "$LANGUAGES"

# Check if any translation files were generated
TRANSLATION_FILES=$(find . -name "llm_translation_task_*.json" | wc -l)
if [ "$TRANSLATION_FILES" -eq 0 ]; then
    echo "✅ All translations are complete! No work needed."
    exit 0
fi

echo "✅ Generated $TRANSLATION_FILES translation task file(s)"

# Step 2: Translate using Gemini LLM
echo ""
echo "🤖 Step 2: Translating with Gemini AI..."
python /action/translate_with_llm.py --api-key "$GEMINI_API_KEY"

# Step 3: Apply translations back to .xcstrings files
echo ""
echo "📝 Step 3: Applying translations to .xcstrings files..."
python /action/apply_translations.py --folder "$SOURCE_FOLDER"

# Step 4: Add regional variants
echo ""
echo "🌐 Step 4: Adding regional variants..."
python /action/add_regional_variants.py --folder "$SOURCE_FOLDER"

# Clean up translation task files
echo ""
echo "🧹 Cleaning up temporary files..."
rm -f llm_translation_task_*.json

# Step 5: Create PR with changes
echo ""
echo "📤 Step 5: Creating pull request..."

# Authenticate GitHub CLI
if [ -z "$GITHUB_TOKEN" ]; then
    echo "❌ Error: GITHUB_TOKEN is required to create a PR"
    exit 1
fi

# GitHub CLI will automatically use the GITHUB_TOKEN environment variable
echo "✅ Using GITHUB_TOKEN for authentication"

# Configure git
git config --global --add safe.directory /github/workspace
git config --global user.name "github-actions[bot]"
git config --global user.email "github-actions[bot]@users.noreply.github.com"
echo "✅ Git configured"

# Create a new branch
BRANCH_NAME="localization/auto-translate-$(date +%Y%m%d-%H%M%S)"
echo "📝 Creating branch: $BRANCH_NAME"
git checkout -b "$BRANCH_NAME" 2>&1 || {
    echo "❌ Error: Failed to create branch"
    exit 1
}
echo "✅ Branch created"

# Stage changes (recursively find and add all .xcstrings files)
echo "📝 Staging .xcstrings files from $SOURCE_FOLDER..."
find "$SOURCE_FOLDER" -name "*.xcstrings" -exec git add {} \;
echo "✅ Files staged"

# Check if there are changes to commit
if git diff --staged --quiet; then
    echo "✅ No changes to commit (translations may have already been applied)"
    exit 0
fi

# Count number of translations
TRANSLATIONS_COUNT=$(git diff --staged --numstat | awk '{sum += $1 + $2} END {print sum}')
echo "📊 Changes detected: ~$TRANSLATIONS_COUNT lines"

# Commit changes
echo "📝 Committing changes..."
git commit -m "🌍 Auto-translate localization strings

- Translated missing strings for: $LANGUAGES
- Added regional variants
- Generated by LLM-Powered Localization Action" 2>&1 || {
    echo "❌ Error: Failed to commit changes"
    exit 1
}
echo "✅ Changes committed"

# Push branch
echo "📤 Pushing branch to origin..."
git push origin "$BRANCH_NAME" 2>&1 || {
    echo "❌ Error: Failed to push branch"
    exit 1
}
echo "✅ Branch pushed successfully"

# Determine base branch (use GITHUB_REF_NAME if available, otherwise detect main/master)
BASE_BRANCH="${GITHUB_REF_NAME:-main}"
if [ -z "$GITHUB_REF_NAME" ]; then
    # Try to detect the default branch
    if git show-ref --verify --quiet refs/remotes/origin/main; then
        BASE_BRANCH="main"
    elif git show-ref --verify --quiet refs/remotes/origin/master; then
        BASE_BRANCH="master"
    fi
fi

echo "📝 Creating PR with base branch: $BASE_BRANCH"

# Create PR using GitHub CLI
PR_URL=$(gh pr create \
    --title "🌍 Auto-translate localization strings" \
    --body "This PR contains automatically generated translations using Google Gemini AI.

## Summary
- **Languages**: $LANGUAGES
- **Files Modified**: $(git diff --name-only HEAD~1 | wc -l)
- **Lines Changed**: ~$TRANSLATIONS_COUNT

## What's included
- ✅ Missing translations filled in
- ✅ Regional variants added (en-AU, pt-BR, es-419, etc.)

## Review Notes
Please review the translations for accuracy and cultural appropriateness. The AI-generated translations are a starting point and may need refinement.

---
*Generated by [LLM-Powered Localization Action](https://github.com/your-username/karo-localization-llm)*" \
    --base "$BASE_BRANCH" 2>&1) || {
    echo "❌ Error: Failed to create PR"
    echo "PR creation output: $PR_URL"
    exit 1
}

# Extract PR number from URL
PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')

echo "✅ Pull request created: $PR_URL"
echo "translations-count=$TRANSLATIONS_COUNT" >> "$GITHUB_OUTPUT"
echo "pr-number=$PR_NUMBER" >> "$GITHUB_OUTPUT"

echo ""
echo "================================================"
echo "🎉 Localization workflow completed successfully!"
echo "================================================"
